// Building class descriptions (NYC DOF taxonomy)
const BUILDING_CLASS_MAP = {
  A0: 'Cape Cod / Single Family',
  A1: 'Two-Story Frame Single Family',
  A2: 'One-Story Frame Single Family',
  A3: 'Large Single Family',
  A4: 'City-owned Single Family',
  A5: 'Attached Single Family',
  A6: 'Seasonal Single Family',
  A7: 'Cardboard House',
  A8: 'Bungalow Single Family',
  A9: 'Miscellaneous Single Family',
  B1: 'Two-Family Brick',
  B2: 'Two-Family Frame',
  B3: 'Two-Family Converted',
  B9: 'Miscellaneous Two-Family',
  C0: 'Walk-Up Apartments (3–4 Units)',
  C1: 'Walk-Up Apartments (5+ Units) — Over 6 Stories',
  C2: 'Walk-Up Apartments (5+ Units) — Under 6 Stories',
  C3: 'Walk-Up Apartments — Converted',
  C4: 'Old Law Tenements',
  C5: 'Converted Dwellings',
  C6: 'Walk-Up — Cooperative',
  C7: 'Walk-Up — Condominium',
  C8: 'Walk-Up — Miscellaneous',
  C9: 'Garden Apartments',
  D0: 'Elevator Apartments — Cooperative, Conversion',
  D1: 'Elevator Apartments — Semi-Fireproof',
  D2: 'Elevator Apartments — Artists-In-Residence',
  D3: 'Elevator Apartments — Fireproof (No Central Heat)',
  D4: 'Elevator Apartments — Cooperative',
  D5: 'Elevator Apartments — Converted',
  D6: 'Elevator Apartments — Fireproof with Central Heat',
  D7: 'Elevator Apartments — Condominium',
  D8: 'Elevator Apartments — Cooperative; Conversion',
  D9: 'Elevator Apartments — Miscellaneous',
  E1: 'Factories — On Waterfront',
  E2: 'Factories — With No Elevator',
  E3: 'Factories — With Elevator',
  E4: 'Industrial Small Plants',
  E7: 'Warehouse',
  E9: 'Miscellaneous Industrial',
  F1: 'Store Buildings (Taxpayers)',
  F2: 'Store Buildings — Fireproof',
  F4: 'Store Buildings — Converted',
  F5: 'Store Buildings — Warehouse/Loft Conversion',
  F8: 'Store Building — Loft',
  F9: 'Miscellaneous Store Building',
  G0: 'Garage (4 or more stories)',
  G1: 'All Parking Garages',
  G2: 'Auto Body/Collision or Auto Repair',
  G3: 'Gas Station with Retail',
  G4: 'Gas Station No Retail',
  G5: 'Gas Station — Unattended',
  G6: 'Garage — Clean/Green',
  G7: 'Garage — Miscellaneous',
  G9: 'Garage — Miscellaneous',
  H1: 'Hotel — Luxury Type',
  H2: 'Hotel — Full Service',
  H3: 'Hotel — Limited Service',
  H4: 'Hotel — Motel',
  H5: 'Hotel — Sheraton-type',
  H6: 'Hotel — Apartment Hotel',
  H7: 'Hotel — Apartment Hotel — Condominium',
  H8: 'Hotel — Miscellaneous',
  H9: 'Hotel — Miscellaneous',
  I1: 'Hospitals',
  I2: 'Infirmary',
  I3: 'Dispensary',
  I4: 'Staff Facilities',
  I5: 'Health Center, Child Center, Clinic',
  I6: 'Nursing Home',
  I7: 'Adult Care Facility',
  I9: 'Miscellaneous',
  J1: 'Theater, Movie',
  J2: 'Theater, Legitimate / Auditorium',
  J4: 'Amphitheater / Open Air Theater',
  J5: 'Theater, Amusement',
  J6: 'Theater (Not Used for Producing Shows)',
  J8: 'Concert Hall',
  J9: 'Miscellaneous Entertainment',
  K1: 'One Story Retail Building',
  K2: 'Multi-story Retail Building',
  K3: 'Multi-use Retail Building',
  K4: 'Predominant Use — Retail with Apartments',
  K6: 'Shopping Centers with Parking',
  K9: 'Miscellaneous Store Building',
  L1: 'Loft — Over 8 Stories',
  L2: 'Loft — Less Than 8 Stories',
  L3: 'Loft — Semi-Fireproof',
  L9: 'Loft — Miscellaneous',
  M1: 'Churches, Synagogues, Etc.',
  M2: 'Mission / Gospel House',
  M3: 'Parsonage, Rectory',
  M4: 'Convent',
  M9: 'Miscellaneous Religious',
  N1: 'Asylums',
  N2: 'Home for Aged',
  N3: 'Orphanage',
  N4: 'Detention House for Wayward',
  N9: 'Miscellaneous Institution',
  O1: 'Office Only Building — 1 to 6 Stories',
  O2: 'Office Only Building — 7 to 19 Stories',
  O3: 'Office Only Building — 20 Stories or More',
  O4: 'Office Building with Stores',
  O5: 'Office Building with Apartments',
  O6: 'Office Building — Suite Hotel',
  O7: 'Professional Building',
  O8: 'Office Building — Loft',
  O9: 'Miscellaneous Office Building',
  P1: 'Concert Hall',
  P2: 'Lodge Room',
  P3: 'YWCA, YMCA, YWHA, YMHA, PAL',
  P4: 'Beach Club',
  P5: 'Country Club',
  P6: 'Stadium, Race Track, Baseball Field',
  P7: 'Tennis Court',
  P8: 'Marina / Yacht Club',
  P9: 'Miscellaneous Places of Public Assembly',
  Q0: 'Parks — City',
  Q1: 'Parks — Amusement',
  Q2: 'Playground',
  Q3: 'Outdoor Pool',
  Q4: 'Beach',
  Q5: 'Golf Course',
  Q6: 'Stadium',
  Q7: 'Tennis Court',
  Q8: 'Marina / Yacht Club',
  Q9: 'Miscellaneous',
  R0: 'Condominium — Billing Lot',
  R1: 'Condo — Residential (Walk-Up)',
  R2: 'Condo — Residential (Elevator)',
  R3: 'Condo — Residential (Conversion)',
  R4: 'Condo — Residential (Conversion)',
  R5: 'Condo — Miscellaneous Residential',
  R6: 'Condo — Residential',
  R7: 'Condo — Commercial',
  R8: 'Condo — Commercial',
  R9: 'Condo — Miscellaneous',
  S0: 'Primarily Single Family with Store',
  S1: 'Primarily Two-family with Store',
  S2: 'Primarily Walk-up with Store',
  S3: 'Primarily Walk-up Apts with Store',
  S4: 'Primarily Elevator Apt with Store',
  S5: 'Primarily Attached or Semi-detached',
  S9: 'Single or Double with Store (Miscellaneous)',
  T1: 'Transportation — Air Rights',
  T2: 'Piers / Wharves',
  U0: 'Utility — Company Land',
  U1: 'Bridge / Tunnel / Highway',
  U2: 'Gas / Electric Utility',
  U3: 'Telephone Utility',
  U4: 'Railroad / Rights of Way',
  U5: 'Sewer / Water Utility',
  U6: 'Urban Renewal',
  U7: 'City-owned Property',
  U8: 'Revocable Consents',
  U9: 'Miscellaneous',
  V0: 'Zoned Residential — Not Manhattan',
  V1: 'Zoned Commercial or Manhattan Residential',
  V2: 'Zoned Commercial Adjacent to Class 1',
  V3: 'Zoned Primarily Residential',
  V4: 'Police or Fire Department',
  V5: 'School Sites or Yards',
  V6: 'Library, Settlement, Hospital',
  V7: 'Port Authority of NY/NJ',
  V8: 'New York State or US Government',
  V9: 'Miscellaneous',
  W1: 'Public Elementary, Junior, or Senior HS',
  W2: 'Parochial School or Charitable School',
  W3: 'Private School',
  W4: 'Training School',
  W5: 'City University',
  W6: 'Other University or College',
  W7: 'Theological Seminary',
  W8: 'Other Educational Facility',
  W9: 'Miscellaneous',
  Y1: 'Fire Department',
  Y2: 'Police Department',
  Y3: 'Prison or Jail',
  Y4: 'Military / Naval Installation',
  Y6: 'Pier / Wharf',
  Y7: 'Easement',
  Y8: 'Cemetery',
  Y9: 'Miscellaneous Government / City Owned',
  Z0: 'Tennis or Squash Court (not Park)',
  Z1: 'Court House',
  Z2: 'Public Parking Area',
  Z3: 'Post Office',
  Z4: 'Foreign Government',
  Z5: 'United Nations',
  Z7: 'Easement',
  Z8: 'Cemetery',
  Z9: 'Other',
}

export function getBuildingClassDescription(code) {
  if (!code) return null
  const upper = code.toUpperCase()
  return BUILDING_CLASS_MAP[upper] || `Building Class ${upper}`
}

// Land use codes
const LAND_USE_MAP = {
  '01': 'One & Two Family Buildings',
  '02': 'Multi-Family Walk-Up Buildings',
  '03': 'Multi-Family Elevator Buildings',
  '04': 'Mixed Residential & Commercial',
  '05': 'Commercial & Office Buildings',
  '06': 'Industrial & Manufacturing',
  '07': 'Transportation & Utility',
  '08': 'Public Facilities & Institutions',
  '09': 'Open Space & Recreation',
  '10': 'Parking Facilities',
  '11': 'Vacant Land',
}

export function getLandUseDescription(code) {
  if (!code) return null
  const padded = String(code).padStart(2, '0')
  return LAND_USE_MAP[padded] || `Land Use ${padded}`
}

// Owner type codes
const OWNER_TYPE_MAP = {
  C: 'City-owned',
  M: 'Mixed city & private',
  O: 'Other (public authority, state, federal)',
  P: 'Private',
  X: 'Fully tax exempt',
}

export function getOwnerTypeDescription(code) {
  if (!code) return 'Private'
  return OWNER_TYPE_MAP[code.toUpperCase()] || code
}

// Format currency
export function formatCurrency(val) {
  if (!val && val !== 0) return '—'
  const n = Number(val)
  if (isNaN(n)) return '—'
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(2)}M`
  if (n >= 1_000) return `$${(n / 1_000).toFixed(0)}K`
  return `$${n.toLocaleString()}`
}

// Format number with commas
export function formatNum(val, suffix = '') {
  if (!val && val !== 0) return '—'
  const n = Number(val)
  if (isNaN(n) || n === 0) return '—'
  return n.toLocaleString() + (suffix ? ` ${suffix}` : '')
}
